### ISSUE TITLE
false positive on name 

### ISSUE THREAD

**Issue by f17208** [voku/anti-xss#113]
#### What is this feature about (expected vs actual behaviour)?
Trying to validate a string containing a person's name, the method xss_clean returns a modified string, please see the following screens: 

<img width="332" alt="Screenshot 2022-11-10 at 17 28 06" src="https://user-images.githubusercontent.com/56392140/201151820-ff5d9ed9-96f0-435e-82a1-f3920baf5101.png">

<img width="130" alt="Screenshot 2022-11-10 at 17 27 04" src="https://user-images.githubusercontent.com/56392140/201151805-6470d778-2812-4a70-a586-211fffdbe07a.png">

#### How can I reproduce it?
Here's the minimum code I can provide for reproducing the issue:
```
$antiXss = new AntiXSS();
$value = "Eva L'Host";
$cleaned = $antiXss->xss_clean($value);
dump($value, $cleaned);
```

#### Any additional information?
I tried with modified versions of the string, like "Eve L'Host" and it's validated correctly. I guess the library is interpreting the string "Eva L'Host" as an attempt to use "eval". 

I found a test (https://github.com/voku/anti-xss/blob/master/tests/XssTest.php) that should ensure that "ordinary strings" containing the word "eval" are validated correctly, but I guess different strings with spaces and single quotes may lead to false positives.

**Comment by voku** [comment]
Thanks for the bug report, fixed in version: 4.1.40 (2023-02-11)
