### ISSUE TITLE
Cleaner produces invalid markup

### ISSUE THREAD

**Issue by JANorman** [voku/anti-xss#12]
As per [this unit test](https://github.com/voku/anti-xss/blob/f442e9853fbb099e019068e414f1667a0d4e1000/tests/XssTestArray.php#L43), your library converts 

````html
<td rowspan="2" class="mugwump" style="background-color: rgb(255, 204 204);">Bar</td>
````

into 

````html
<td rowspan="2" class="mugwump"  rgb(255, 204 204);">Bar</td>
````

This is invalid HTML markup. Can you confirm if this is the intended behaviour?

Many thanks

**Comment by voku** [comment]
thx for the bug-report ... fixed.
