### ISSUE TITLE
Tag img is allowed

### ISSUE THREAD

**Issue by victorleal** [voku/anti-xss#13]
I'm trying to remove **any** HTML tag, but `img`tags are allowed.

I was looking the code but I couldn't found a method to remove `img` tags. The only method that I found was one to add attributes to be removed (`addEvilAttributes`).

Isn't there a way to remove `img` tags?

**Comment by voku** [comment]
What is with <picture>-tags or <svg>-tags, background-images via style etc. ... it isn't so simple to remove all "images". If you need a more flexible solution, take a look at "http://htmlpurifier.org/" they use the concept of "whitelisting", so you can define allowed HTML-tags.

**Comment by victorleal** [comment]
I mean `img` HTML tags, not background-images but the tag itself like `<img src="a.jpg">`.

I know that is not that easy to remove all images and your package is very good on sanitizing HTML, but I need something more flexible. 

I was already thinking about using HTML Purifier and I'll try it!

Thanks!

**Comment by voku** [comment]
I mean not only background-images, also the new picture images (https://developer.mozilla.org/de/docs/Web/HTML/Element/picture) or svg images... so I think a whitelist with some allowed tags are the better option in this case.
