### ISSUE TITLE
question about usage

### ISSUE THREAD

**Issue by voltan** [voku/anti-xss#18]
Hello

We think about use this class on our cms ( https://github.com/pi-engine/pi ) Instead of this filter ( https://github.com/pi-engine/pi/blob/develop/lib/Pi/Filter/XssSanitizer.php and https://github.com/pi-engine/pi/blob/develop/lib/Pi/Security/Xss.php) for make support better php7

Just I have question, can we make squerty little simpler ? for example we use ckeditor and users make some custom setting ( usually use css codes ) but this project remove all custom css codes , can we manage it?

**Comment by voku** [comment]
Hi, I added an small example into the README file. (Example 5.2)

**Comment by voltan** [comment]
thank you very much, I will test it today

**Comment by voltan** [comment]
I see it , I think it solve our problem, just other question , on tests I setup `AntiXSS.php` and Unicode plugin and didn't use sanfony files and other class , can we just use `AntiXSS` and `Unicode` ?

**Comment by voku** [comment]
No, the Symfony Polyfills (https://github.com/symfony/polyfill) are needed on some servers, because of maybe missing php-libraries. So we need the polyfill for e.g. "mb_*" so that we can convert all HTML-Entities on all servers (security by default).

**Comment by voltan** [comment]
Thank for reply , we use zend fremwork , can I use zend intend of Symfony ?

than we need copy all of this class : 
* ircmaxell
* paragonie
* symfony
* voku

and can you please tell me method for test all of class install true on no?

thanks

**Comment by voku** [comment]
With version 4.0.0 of AntiXSS (PHP >= 7.0 support) we got rid of many dependencies and fallbacks.

And if your servers don't need the polyfills you can use it without any extra libs. You can add something like that in you ```composer.json```-file.

```
    ...
    "replace": {                                                                 
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-intl-grapheme": "*",
        "symfony/polyfill-intl-normalizer": "*",
        "symfony/polyfill-mbstring": "*"                                      
    },
    ...
```
