### ISSUE TITLE
Issue with normalize_whitespace and normalize_msword

### ISSUE THREAD

**Issue by yang-jandro** [voku/anti-xss#19]
How come `AntiXSS::clean()` runs `UTF::clean()` with normalize_whitespace and normalize_msword set to true? 

Asking because I'm trying to use the library to check for XSS attacks and send myself warnings. I have it setup like `if ($value != $this->anti_xss->xss_clean($value)) { // send message }`, but if $value has utf8 spaces or dashes, they'll be converted and returned by AntiXSS.

**Comment by voku** [comment]
We need to convert the string, so that we can detect the XSS attack. Here is an example via "isXssFound()" (available in version v2.1.0) -> https://github.com/voku/anti-xss

**Comment by yang-jandro** [comment]
Thanks for the quick response and solution. Out of curiosity, can you elaborate why normalizing is required vs just checking against utf whitespaces/ mswords?

**Comment by yang-jandro** [comment]
So only other problem with `isXssFound` is html entities get auto decoded by `xss_clean`. So if the original string has any html entity (e.g. `&amp;`) it'll give a false positive. We'll probably want to move setting the [$str_backup](https://github.com/voku/anti-xss/blob/master/src/voku/helper/AntiXSS.php#L1961) to under the [`decode_string`](https://github.com/voku/anti-xss/blob/master/src/voku/helper/AntiXSS.php#L1964) call.

**Comment by voku** [comment]
👍 done in version 2.1.1 -> https://github.com/voku/anti-xss/commit/2bac006af1a970e59ddb39391afb5f241ed98421
