### ISSUE TITLE
PHP 5.5 with mbstring and special characters breaks output

### ISSUE THREAD

**Issue by eelco2k** [voku/anti-xss#21]
There is a problem when using PHP Version 5.5.9-1ubuntu4.21 and the UTF8 helper class.

`require_once('../vendor/autoload.php');
use voku\helper\AntiXSS as AntiXSS;
$antiXss = new AntiXSS();
$badstring = "éæ";
$clean_string = $antiXss->xss_clean($badstring);
echo $clean_string;
`
printsout: Ã

So i guess something goes wrong with to much decoding after digging i found that it goes wrong in the UTF8 helper class specific the function to_utf8($str, $decodeHtmlEntityToUtf8 = false);

I will attach the mbstring phpinfo here below:

mbstring

Multibyte Support	enabled
Multibyte string engine	libmbfl
HTTP input encoding translation	enabled
libmbfl version	1.3.2

mbstring extension makes use of "streamable kanji code filter and converter", which is distributed under the GNU Lesser General Public License version 2.1.

Multibyte (japanese) regex support	enabled
Multibyte regex (oniguruma) backtrack check	On
Multibyte regex (oniguruma) version	5.9.2

Directive	Local Value	Master Value
mbstring.detect_order	no value	no value
mbstring.encoding_translation	On	On
mbstring.func_overload	6	6
mbstring.http_input	UTF-8	UTF-8
mbstring.http_output	pass	pass
mbstring.http_output_conv_mimetypes	^(text/|application/xhtml\+xml)	^(text/|application/xhtml\+xml)
mbstring.internal_encoding	UTF-8	UTF-8
mbstring.language	neutral	neutral
mbstring.strict_detection	Off	Off
mbstring.substitute_character	no value	no value

**Comment by eelco2k** [comment]
$max = strlen($str); --> shows "3"
$max = mb_strlen($str, '8bit'); --> shows "5" (which is correct for analysing unicode character)

And this is because we use de mbstring.func_overload in our php.ini
So i guess it would be better to always use: 

`$max = mb_strlen($str, '8bit');`

So that we always count in bytes.

**Comment by voku** [comment]
Hi... I already answered on your pull-request, here -> https://github.com/voku/portable-utf8/pull/54#issuecomment-284896475
