### ISSUE TITLE
How install?

### ISSUE THREAD

**Issue by Kevin20** [voku/anti-xss#22]

**Comment by Kevin20** [comment]
It say: Fatal error: Uncaught Error: Class 'voku\helper\AntiXSS' not found

code:
 <?php

            use voku\helper\AntiXSS;
            $antiXss = new AntiXSS();
            $harm_string = "Hello, i try to <script>alert('Hack');</script> your site";
            $harmless_string = $antiXss->xss_clean($harm_string);

            ?>

**Comment by voku** [comment]
You need to include the "composer"-autoloader... here is the source-code from a demo-application, maybe this can help you. 

https://github.com/voku/anti-xss--demo/blob/master/app/autoload.php

... and here the documentation of composer :) 

https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by Kevin20** [comment]
Thanks voku!
