### ISSUE TITLE
xss_clean removes '+'

### ISSUE THREAD

**Issue by rophini** [voku/anti-xss#23]
We use anti-xss in our product search forms. We have a product that's called 'GOM-KC-350+550 '. But the '+'-sign is removed from the product name when we pass the form input through the xss_clean function ("GOM-KC-350+550"  => "GOM-KC-350 550"). Can we prevent this?

thanks in advance!

**Comment by voku** [comment]
I have fixed the issue in version 2.1.3 | https://github.com/voku/anti-xss/tree/2.1.3

**Comment by rophini** [comment]
Thanks!
