### ISSUE TITLE
Error UTF8

### ISSUE THREAD

**Issue by gittiago12** [voku/anti-xss#24]
Have downloaded and use antixss in my project, but have a error UTF8 not exist

**Comment by voku** [comment]
Can you install it via composer? Take a look at the README... 

If this isn't a option for you, I can build a package 📦 (Phar) with all vendor libs included.

**Comment by gittiago12** [comment]
i've forget using composer. thanks for help

2017-05-10 3:10 GMT-03:00 Lars Moelleken <notifications@github.com>:

**Comment by gittiago12** [comment]
i've forget using composer. thanks for help

**Comment by voku** [comment]
no problem, have a nice day :)
