### ISSUE TITLE
Fatal error: Uncaught Error: Class 'UTF8' not found 

### ISSUE THREAD

**Issue by hunnomad** [voku/anti-xss#35]
Hi,

I would like use your anti-xss library, but I have an error message. So, I write a native php code and included your AntiXSS.php.

`include "inc/AntiXSS.php";`

Then I call:

`$antiXss = new AntiXSS();`

I put the `$antiXss->xss_clean($input);`

Result: 

`Fatal error: Uncaught Error: Class 'UTF8' not found in include\AntiXSS.php:1933 Stack trace: #0 [internal function]: AntiXSS->_decode_entity(Array) #1 include\AntiXSS.php(2472): preg_replace_callback('/<\\w+.*+/si', Array, 't\xC5\xB1zolt\xC3\xB3<scipt...') #2 include\AntiXSS.php(1985): AntiXSS->_decode_string('t\xC5\xB1zolt\xC3\xB3<scipt...') #3 include\AntiXSS.php(2907): AntiXSS->_do('t\xC5\xB1zolt\xC3\xB3<scipt...') #4 modules\keres\keres_index.php(22): AntiXSS->xss_clean('t\xC5\xB1zolt\xC3\xB3<scipt...') #5 engine.php(19): include('\m...') #6 index.php(216): include('...') #7 {main} thrown in include\AntiXSS.php on line 1933`

Can you help me?

**Comment by voku** [comment]
Can you install it via composer? Because otherwise the dependencies won't be installed automatically.

**Comment by hunnomad** [comment]
Yes, I installed with composer. But the /vendor/voku/src/anti-xss/ directorxy included one file. I don't see other files.

**Comment by hunnomad** [comment]
include $_SERVER['DOCUMENT_ROOT']."/vendor/autoload.php";
$antiXss = new AntiXSS();

Fatal error: Class 'AntiXSS' not found in /data/***/_temp/index.php on line 9

[http://hisz.rsoe.hu/_temp/](url)

**Comment by voku** [comment]
Please try "require_once" instead of "include", so you can be sure that you really included the vendor-autoloader.

**Comment by hunnomad** [comment]
Ok. So, my enviroment:

Debian 7
PHP 5.6

My test code:

```
<?php
# Fejlesztői cucc, hibajelentés be/ki ------------------------------------------------
error_reporting(E_ALL);
ini_set("display_errors", 1);
# Fejlesztői cucc, hibajelentés be/ki ------------------------------------------------

require_once($_SERVER['DOCUMENT_ROOT']."/vendor/autoload.php");

$antiXss = new AntiXSS();

?>
```
Result:

`Fatal error: Class 'AntiXSS' not found in /data/hisz.rsoe.hu/_temp/index.php on line 9`

I will try this class in PHP 7.0 environment, I hope, this great class will be working... Soon I'll be ... thank you for your patience

**Comment by voku** [comment]
can you try to include the "autoload.php" via absolute path? e.g.:

```php
require_once __DIR__ . '/vendor/autoload.php';
```

take a look at the tests: https://github.com/voku/anti-xss/blob/master/tests/bootstrap.php

**Comment by hunnomad** [comment]
Hmmm.....

```
<?php
# Fejlesztői cucc, hibajelentés be/ki ------------------------------------------------
error_reporting(E_ALL);
ini_set("display_errors", 1);
# Fejlesztői cucc, hibajelentés be/ki ------------------------------------------------

require_once dirname(__DIR__) . '/media_pdo/vendor/autoload.php';

$antiXss = new AntiXSS();

?>
```

`Fatal error: Uncaught Error: Class 'AntiXSS' not found in `

**Comment by voku** [comment]
The class isn't in the root namespace \ so you need to set the namespace. Take a look at the tests. 

use voku\helper\AntiXSS;

PS: I will update the README (and if you use e.g. "phpstorm eap", then the IDE will help you with the namespaces by e.gm auto import the namespace while typing)

**Comment by hunnomad** [comment]
Thank you, that was the solution!
