### ISSUE TITLE
clean src element wrongly

### ISSUE THREAD

**Issue by Peyman-Manutd** [voku/anti-xss#41]
Hi,
I've developed a UGC service with laravel that users can publish posts.
I've used this package to prevent xss, and used `xss_clean` method in validation before post can published.
But sometimes there are some issues that clean wrong contents.
For example:
**before xss_clean**: ``<img src="https://files.virgool.io/upload/users/5891/posts/ndj7j0vhy6zd/ebrtae7ktbce.png" alt="توییتر " />``

**after xss_clean:**  ``<img src="" />``

in this post there are 4 img tags but `xss_clean` cleaned only this one !!

Or in another post:
**before**: ``<img src="https://files.virgool.io/upload/users/9474/posts/bpdk334ljqgz/i9jlbhiwxbjl.jpeg" alt="فضا (فضای سفید یا خالی) -  Space"``/>

**after**: ``<img src="" />``

**Comment by voku** [comment]
Can you provide the complete html example maybe in a single html file, thanks?

**Comment by Peyman-Manutd** [comment]
Sure.

[xss_issue_sample_post.zip](https://github.com/voku/anti-xss/files/2848210/xss_issue_sample_post.zip)

**Comment by voku** [comment]
I have added a test case here https://github.com/voku/anti-xss/commit/985b47f7c414190e9097585981d4337965956b8b ... but I can't see the problem in the test? Do you use the latest version? v4.1.4

**Comment by Peyman-Manutd** [comment]
Yes, I use v4.1.4
I've attached a sample post before and after using xss_clean.

[sample post before and after using xss_clean.zip](https://github.com/voku/anti-xss/files/2849028/sample.post.before.and.after.using.xss_clean.zip)

**Comment by voku** [comment]
I don't think that this is a before - after dump of the effected html, because e.g. the css and the font are different in this files?

Can you provide the html complete example as minimal as possible, so that I can test it?

**Comment by Peyman-Manutd** [comment]
Heres three minimal samples
[minimal samples.zip](https://github.com/voku/anti-xss/files/2859582/minimal.samples.zip)

And these are screenshots from [diffchcker](https://www.diffchecker.com) shows changes before and after using `xss_clean`

**sample 2:**
![sample 2](https://user-images.githubusercontent.com/11339828/52700040-5f299b80-2f8c-11e9-9c07-719adb8cc867.png)


**sample 3:**
![sample 3](https://user-images.githubusercontent.com/11339828/52700181-b6c80700-2f8c-11e9-9105-4d65b86377e3.png)

**Comment by voku** [comment]
Thanks for the bug report and thanks for the screenshot :+1: I tested it first with your html encoded sample files :man_facepalming: ... so the problem was a regex ```(?:\(.+([^\)]*?)(?:\)|$)``` where I checked not only the content from "src=.*".

PS: fixed in version 4.1.5
