### ISSUE TITLE
False positive in string

### ISSUE THREAD

**Issue by gioialorusso** [voku/anti-xss#43]
Hello,
I am using the library to prevent XSS attacks. When I input the string `Mondragon`, the string is recognized as XSS because it contains the word `ondrag`, which is in the `$_never_allowed_str_afterwards` list.
I was wondering if there is any chance in improving the detection algorithm, maybe an equal sign shoud follow some of the `$_never_allowed_str_afterwards` words? (For example `onDrag=` instead of `onDrag`)
Or maybe would it be possible to have a method to customize the `$_never_allowed_str_afterwards` list, in order to remove some of the words in it? I see that is it possible to remove evil html tags (`removeEvilHtmlTags`) and attributes (`removeEvilAttributes`) but no modification is allowed on the `$_never_allowed_str_afterwards` list.

Thanks for the help,

**Comment by voku** [comment]
Thanks for the bug report, fix in version 4.1.6.

---

I've added a regex ```(?:onDrag)(\s*\W|$)``` so we'll catch the xss attack if there's no standard letter after the "on"-event string.

example -> https://regex101.com/r/baAD4r/1

**Comment by gioialorusso** [comment]
Hello,
thanks for your fix, the problem is now fixed, but I have another case of false positive with the string "DE VAL HERNANDEZ" or "DE VAL LOPEZ": I think it could be for the presence of the substring "eval" in it.
Any chance to remove also this false positive?
Thanks,

**Comment by voku** [comment]
Thanks also for this bug report, fixed in version 4.1.7.

---

We try to compact some bad exploded words like "j a v a s c r i p t", because some browsers ignore (some kind of) white-space. The problem was that we also match e.g. "fooj a v a s c r i p t". So now we only want to do this when it is followed by a non-word character. And if there are no char at the start of the string.

**Comment by gioialorusso** [comment]
Hello,
thanks, I have no more problem on "DE VAL" strings. 
I am sorry to bother with all these bug reports, but I noticed also that the email ` xxxnonstop@hotmail.com`  causes a false positive. Could it be due to the onstop string, followed by non-standard "@" character? should the @ character be included into the "standard" characters to be allowed after the on-event string?

**Comment by gioialorusso** [comment]
Also, the string MONDRAGÓN is causing an xss found. Is it possible that the accented letter causes the problem?

**Comment by voku** [comment]
I like your bug reports :) -> fixed in version 4.1.8.

---

I was again working with non unicode regex :/ ... I fixed that and added a exception for the "@"-char. Happy easter && happy coding!

**Comment by gioialorusso** [comment]
Thanks! I will try the new version of the library in production after easter, just to have time to monitor it :)
Thanks for your time and happy easter to you too!

**Comment by gioialorusso** [comment]
Hello,
I have not yet tested the new version of the library in production, but in test environment I have noticed that also the following strings
`ANAMNESI E VAL.DEFINITE BREVI ORTO`
`ANAMNESI E VAL DEFINITE BREVI ORTO`
are causing a false positive.
It could be because of the `.` character after the `E VAL` string as well as the space character.

**Comment by voku** [comment]
fixed in version 4.1.10

---

I changed the regex, so that "!", "?", "." + unicode chars are whitelisted for this use case.

**Comment by gioialorusso** [comment]
Thanks, all the cases mentioned before are now OK.
I have a new case with this string:
`cyyhqLRMvBs:APA91bH1ueQlBr8GXbQxNw9SpzldRAeYK4mw-Yqhw44v7oEoRgxyoFAfQc_2A3dc6X_vp3HpmPGh4NAItAAyv9pvoQbJZXUotjX0427y1hG_vCtr34UnEecqAGsXwkevitdHZIp9juRC`
recognized as XSS positive.
I don't know which is the step that cause the XSS found, but if you remove the `:` character in the string, no XSS is found.
Any idea why the string in marked as XSS positive?
Thanks,

**Comment by voku** [comment]
fixed in version 4.1.11

---

fixed via https://github.com/voku/anti-xss/commit/5e131105bc74803aae616702099ab6996bd24ce9

**Comment by rafaelmaiolla** [comment]
I saw that this was fixed for string like `mondragon`, but I would like to know if the following is an issue or an expected behavior when the `ondrag` is at the beginning of the string:

ondragonsomething -> Stripped - results in "onsomething"

Is this expected?

**Comment by rafaelmaiolla** [comment]
I just open a new issue for theses - #52
