### ISSUE TITLE
Tags being stripped after <img />

### ISSUE THREAD

**Issue by gabriel-felipe** [voku/anti-xss#46]
Hi, 

I'm having an issue where any html tag that appears after an img tag gets completely stripped, including content. 

For example: 

```
h1. test

Content for this page is not yet entered.
<a >test</a>
<div class=\'test\'> Test Div </div>
<img src=\'http://google.com\'&nbsp;class=\'test\'/>
<div class=\'test\'> Test Div </div>
<div class=\'test\'> Test Div </div>
```

Gets stripped to:

```
h1. test

Content for this page is not yet entered.
<a >test</a>
<div class=\'test\'> Test Div </div>
<img />
<> >
<> >
```

Code example:

```php
$antiXss = new AntiXSS();
$antiXss->removeEvilAttributes(array('style')); // allow style-attributes
$content = $antiXss->xss_clean($content); // Where content is the first example above.
```

**Comment by voku** [comment]
I don't think that your html is valid. Some browser will try to fix it, but they can't display it as you maybe expect. At least the ```&nbsp;``` is not working at that place, because the keyword ```src``` and ```class``` need a separation.

**Comment by denji** [comment]
@voku Tidy may also be the solution without complicating the code.
