### ISSUE TITLE
Stripping out '+' characters, replacing with " " spaces

### ISSUE THREAD

**Issue by throttlehead** [voku/anti-xss#49]
#### What is this feature about (expected vs actual behaviour)?

"+" characters are being stripped out and turned into spaces. I noticed this was an issue awhile back  #15 and it seems to be happening again with a recent update.

#### How can I reproduce it?

Run any string with a "+" character in it through xss_clean().

#### Does it take minutes, hours or days to fix?

Unsure.

#### Any additional information?

Nope.

**Comment by voku** [comment]
I can not reproduce the issue, maybe you can show me a example or even better write a unit test for that? 

example: 
- https://github.com/voku/anti-xss/commit/735f176c9fd65c42b0f2b1ba5aea12021ad3c058
- https://github.com/voku/anti-xss/commit/eef5433fbf363f0da7e95bbca787585177933cbf

**Comment by throttlehead** [comment]
Terribly sorry mate should of checked our composer.json, have had a head cold the past few days and have been a little foggy. 

We were hard-coded to an older version.
