### ISSUE TITLE
"-->" is detected as xss

### ISSUE THREAD

**Issue by stremlau** [voku/anti-xss#50]
#### What is this feature about (expected vs actual behaviour)?
"-->" is no xss but it is detected as such

#### How can I reproduce it?
```
<?php
require_once('./vendor/autoload.php');
use voku\helper\AntiXSS;

$a = new AntiXSS();
echo $a->xss_clean('foo --> bar');
echo "\n";
echo "xss " . ($a->isXssFound() ? 'found' : 'not found');
echo "\n";
```

#### Does it take minutes, hours or days to fix?
minutes

#### Any additional information?
Thank you for this nice library ;-)

**Comment by voku** [comment]
Thanks for the bug report. :+1: fixed in version 4.1.16
