### ISSUE TITLE
Additional false positives in string

### ISSUE THREAD

**Issue by rafaelmaiolla** [voku/anti-xss#52]
I'm using your library to prevent XSS attacks and I have few cases that seems to be false positive but are removed by the library:

Examples:
* `'onendsomething'` -> results in `'something'`
* `'something onend another thing'` -> results in `'something  another thing'`
* `'something onendtest'` -> results in `'something test'`
* `'something@onendtest'` => results in `'something@test'` - You can also replace @ by - , . ! ' "@ # $ % & * ( ) etc 

If I'm not missing anything, these seem to be normal string.
Is this behavior expected?

**Comment by voku** [comment]
Thanks for the bug report. Fixed in version 4.1.20. 

And if you find more false-positives, please feel free to report them. 

Happy weekend and happy coding! :)
