### ISSUE TITLE
False positive for "on.." prefix in URL

### ISSUE THREAD

**Issue by denisbondar** [voku/anti-xss#54]
```php
$href = '<a href="https://example.com/?onlyEnabled=1">link</a>';
$clean = (new AntiXSS())->xss_clean($href);
$clean == '<a href="">link</a>';
```
I think that falls under this case:
https://owasp.org/www-community/xss-filter-evasion-cheatsheet#Event_Handlers
But at the same time, any word starting with **on...** is recognized as XSS.

**Comment by voku** [comment]
Thanks for the bug report, fixed in version 4.1.22
