### ISSUE TITLE
Escaped <script> tags are removed

### ISSUE THREAD

**Issue by gharlan** [voku/anti-xss#56]
```php
<?php

use voku\helper\AntiXSS;

$content = '
    <pre><code>
        &lt;script&gt;
            foo();
        &lt;/script&gt;
    </code></pre>
';
echo (new AntiXSS())->xss_clean($content);
```

Expected result:

```
    <pre><code>
        &lt;script&gt;
            foo();
        &lt;/script&gt;
    </code></pre>
```

Actual result:

```
    <pre><code>
        
    </code></pre>
```

Is it intended that the already escaped script tags are removed?
If yes, is it really needed, or is it more a "just to be sure"?

**Comment by voku** [comment]
jep, it's "just to be sure" ... and in the new version you can disable this via ...

```php
$antiXss->removeNeverAllowedStrAfterwards(['&lt;script&gt;', '&lt;/script&gt;']);
```

(https://github.com/voku/anti-xss/blob/master/tests/XssTest.php#L147)

... happy coding. :)

**Comment by gharlan** [comment]
Thanks a lot for the quick fix for the other issue and for the config option for this one!
