### ISSUE TITLE
Possibly inconsistent escaping

### ISSUE THREAD

**Issue by andrei-dascalu** [voku/anti-xss#58]
#### What is this feature about (expected vs actual behaviour)?

Basically I have a bit of xml-like string with custom tags. When I pass it through anti-XSS, one of the closing tags is escaped. I am not sure why that particular one falls victim (and why just the closing tag).

In the sample below, </HEADER> is escaped for display, while the rest remains intact. This is inconsistent and it breaks my expected input.

#### How can I reproduce it?

Sample string

```
$myData = '<AWACS>
    <HEADER>
        <SERVICE_ID>BLAH1</SERVICE_ID>
        <DATASOURCE>BLAH2</DATASOURCE>
        <KEY>BLAH3</KEY>
    </HEADER>
    <DATA>
        <REQUEST>
            <FUNCTION NAME="function">
                <PARAM NAME="select">
                    <RELATIES>
                        <RELATIE>
                            <PK />
                            <L NR="55" />
                        </RELATIE>
                        <WHERE TOP="55"/>
                    </RELATIES>
                </PARAM>
            </FUNCTION>
        </REQUEST>
    </DATA>
</AWACS>';
$antiXSS = new AntiXSS();
print_r($antiXSS->xss_clean($myData));
```

#### Does it take minutes, hours or days to fix?

Not sure. I will also investigate, unless it's something obvious.

Thanks!

**Comment by voku** [comment]
Thanks for the bug report. It's fixed in version >= 4.1.25.
