### ISSUE TITLE
img's src="data:image/png;base64," be deleted

### ISSUE THREAD

**Issue by lilalalala** [voku/anti-xss#59]
hi.
i have some contents as `"<img src=base64/> "`. 

but "anti-xss" will delete it, and I can't handle things like that. Can you give me a good solution of this?

Thanks.

**Comment by voku** [comment]
Would this work for you? https://github.com/voku/anti-xss/commit/92eda03a5574cdfd2ddb6a2cb52d0f9762ce9ec8

**Comment by voku** [comment]
Fixed in version 4.1.26
