### ISSUE TITLE
False positive in string <35%

### ISSUE THREAD

**Issue by timmit-nl** [voku/anti-xss#62]
I think it is related: https://github.com/voku/anti-xss/issues/60

#### What is this feature about (expected vs actual behaviour)?
$antiXSS->isXssFound() should be false for string '<35%'

#### How can I reproduce it?
$antiXSS = new \voku\helper\AntiXSS();
$antiXSS->xss_clean('<35%');

$antiXSS->isXssFound() === true

#### Does it take minutes, hours or days to fix?
no clue? :) but it is at the same place as issue https://github.com/voku/anti-xss/issues/60

**Comment by voku** [comment]
Thanks for the bug report, fixed in version 4.1.29.
