### ISSUE TITLE
How allow some condition html content

### ISSUE THREAD

**Issue by Mech-Statham** [voku/anti-xss#63]
As I am facing issue, some of the html content not allowing and it encoding and my html template not working properly.

As I am using some condition content like,
```
<html>
<!-- [if gte mso 9]><xml><o:OfficeDocumentSettings>96</xml><![endif]--> <!-- [if !mso]><!--> <!--<![endif]--> <!-- [if !mso]><!--> <!--<![endif]--><!-- [if IE]><div class="ie-browser"><![endif]-->
```

But when I clean using this library, it converts some tags like,
`<html>&lt;!-- [if gte mso 9]>&lt;xml&gt;<o:OfficeDocumentSettings>96&lt;/xml&gt;&lt;![endif]--&gt; &lt;!-- [if !mso]&gt;&lt;!--&gt; &lt;!--&lt;![endif]--&gt; &lt;!-- [if !mso]&gt;&lt;!--&gt; &lt;!--&lt;![endif]--&gt;&lt;!-- [if IE]&gt;&lt;div class="ie-browser"&gt;&lt;![endif]--&gt;`

I don't want to convert such string` "<!--", "-->", "<xml>","</xml>"`.

Can you please help how I can resolve this?

And any possibility I can remove only below tags and events from harm content like,
<script>, Javascript code, external style tag, javascript events, iframe, object.
Other things I want to allow as it.

**Comment by voku** [comment]
Here is an example: https://github.com/voku/anti-xss/commit/2979ab266637e9ac2f3771405d1fa70b1173dfc7#diff-742333ddea22a32dd5f826ea678fffeb11dbee1945efa6b969cae65f8a0ab4e3R141

Please update to version 4.1.29, so that you can use the ```addDoNotCloseHtmlTags``` method. 

Happy Coding!
