### ISSUE TITLE
Cannot properly install

### ISSUE THREAD

**Issue by FinnAlberts** [voku/anti-xss#79]
I installed this using composer and I can see in the files that it installed. But when I add 
`
use voku\helper\AntiXSS;
require 'vendor/autoload.php';
$antiXss = new AntiXSS();
`
to my code, it returns a 500 error.

When I remove the first line (use voku\helper\AntiXSS;) it gives an error that the AntiXSS class can't be found (Fatal error: Uncaught Error: Class 'AntiXSS' not found in /mnt/web017/e2/63/59998263/htdocs/theater/1_5_1/credentials.php:13 Stack trace: #0 {main} thrown in /mnt/web017/e2/63/59998263/htdocs/theater/1_5_1/credentials.php on line 13)

The autoload.php is referenced correctly.

What am I doing wrong?

Thanks in advance.

**Comment by voku** [comment]
Hi, please take a look into the error log, so that we know why you see the "500" error.

**Comment by FinnAlberts** [comment]
Error has been resolved by moving the code outside of a try catch.
