### ISSUE TITLE
XSS in Angular and AngularJS

### ISSUE THREAD

**Issue by Brenneisen** [voku/anti-xss#93]
Is there a way to detect angular strings? Like this:

`{{'a'.constructor.prototype.charAt=[].join;$eval('x=alert(1)');}}`

`{{constructor.constructor('alert(1)')()}}`

**Comment by voku** [comment]
No, the problem is that frontend frameworks and libs can do whatever they want: e.g. Bootstrap XSS by `data-*` attributes
